---
title: "p8105_hw1_cg3112"
output: github_document
---

#Setup and Libraries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
  d = c(1,2,3,1,2,1,2,3)
```

##Creating a dataframe (Problem 1)
```{r}
plot_df = tibble(
  a = rnorm(8),
  b = a > 0,
  c = ("EasyPeez"),
  e = factor(d,labels=c("I","II","III"))
)

plot_df

```

```{r eval=FALSE}
mean(plot_df)
#This function does not work if the data is not numeric or logical

as.numeric(plot_df)
#This function does not work because list objects cannot be coerced into a double
```

#Manipulating the Tibble and adding variables (End of Problem 1)
```{r warning=FALSE}
mutate(plot_df,
       b_numb = as.numeric(b),
       f_new = b_numb*a,
       b_fact = as.factor(b),
       g_new = b_fact*a,
       b_numb2 = as.numeric(b_fact),
       h_new = b_numb2*a
       )
```

#Creating a data frame (Problem 2)
```{r}
plot_df2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  xy = x + y > 1,
  xy_numb = as.numeric(xy),
  xy_factor = as.factor(xy_numb)
)
```

This tibble has `r nrow(plot_df2)` rows and `r ncol(plot_df2)` columns.
The vector x also has a mean of `r mean(plot_df2$x)`, a median of `r median(plot_df2$x)`, and a standard deviation of `r sd(plot_df2$x)`.

